/* CCAR-F Study — interactive transcripts (English translation of the original sessions).
 * The raw turns, NOT summarized — including wrong answers and their corrections, because that is where the learning happens.
 * The verbatim Korean originals live privately in the workspace (00_META/sessions/*_transcript.md). */

const TRANSCRIPTS = [
  {
    id: 't-d1-s1', dom: 'D1', ses: 'S1', date: '2026-07-13', title: 'Workflow vs Agent (interactive)',
    note: 'English translation of the original session. Raw turns.',
    turns: [
      { who: 'Tutor', text: 'Your verification testbench — a fixed stimulus sequence checked by a scoreboard — is that closer to a workflow or an agent? And by what criterion do you split them?' },
      { who: 'Nick', text: 'The basic fixed sequence is a workflow; workflow tuning and the automatic expansion/execution of each case is an agent.' },
      { who: 'Tutor', text: 'Essentially right — directed test = workflow; coverage-driven auto-expansion = agent-like. The litmus: before running, can you predict/hardcode the path and the step count? Predictable = workflow. The model decides the next step at runtime on feedback = agent. One tweak: executing a fixed sequence is still a workflow — what makes it an agent is the model holding the decision of what to do next. And agency costs more and compounds errors.' },
      { who: 'Tutor', text: 'APPLY. A: ticket → detect language → classify → reply from a fixed template. B: ticket → keep searching docs, checking the account, asking follow-ups until it is resolved. Which is which?' },
      { who: 'Nick', text: 'A workflow, B agent.' },
      { who: 'Tutor', text: 'Both correct. A is fixed steps known up front (workflow); B is open-ended with an unpredictable number of steps that the model drives on feedback (agent).' }
    ]
  },
  {
    id: 't-d1-s2', dom: 'D1', ses: 'S2', date: '2026-07-18', title: 'The 5 Workflow Patterns (interactive)',
    note: 'English translation of the original Korean session. Raw turns — including a wrong answer and its correction, which is where it clicked.',
    turns: [
      { who: 'Tutor', text: 'I gave the meaning of the 5 patterns, then asked you to classify 3 situations. ① Extract key clauses from a contract → write a summary from them → verify the summary against the original. ② Sort an incoming email into {refund / bug / sales} and send each to a dedicated handler. ③ A refactor where the model decides at runtime which files to change → edits each → reassembles.' },
      { who: 'Nick', text: '1 - prompt chaining, 2 - routing, 3 - orchestrator-workers.' },
      { who: 'Tutor', text: 'All three correct. ②↔③ is the most-confused pair on the exam. In your own words, what is the single biggest difference between them? (Hint: who decides the branches, and when?)' },
      { who: 'Nick', text: '③ is the one that grasps the work, autonomously decides the execution process, carries it out, and then aggregates the results. ② only grasps the work and hands tasks to specialist workers.' },
      { who: 'Tutor', text: 'You nailed ③’s autonomy and aggregation. Sharpening: the essence is WHEN the branches are decided. Routing = pick from a predetermined set of bins (classify only, no aggregation). Orchestrator = build the bins at runtime and aggregate. Small correction: routing is not "hand tasks to workers" — it sends one input down one fixed lane; "divide among workers and aggregate" is actually the orchestrator. And the orchestrator is the closest of the five to an agent. Check: a travel assistant decides per request which steps are needed (flights + hotel + visa, or just a train), handles each, and aggregates. Routing or orchestrator?' },
      { who: 'Nick', text: 'Routing. It discriminates the case and splits into "check several things" or "a simple single check".', wrong: true },
      { who: 'Tutor', text: 'This is actually orchestrator — and why it is not routing is the whole lesson. The tells: "decides the needed steps on the fly" + "aggregates". If it were routing, the branches would be fixed in advance ({flights / hotel / refund}), each request goes down exactly one, with no composition or aggregation. Here the combination is not a fixed menu — the model assembles it at runtime → orchestrator. Rule: routing = pick from a fixed set of bins; orchestrator = build the bins on the fly. Re-check: "a travel-agency chatbot classifies a query into {flights / hotel / refund} and sends it to one dedicated consultant." Which is it?' },
      { who: 'Nick', text: 'That is routing.', correct: true },
      { who: 'Tutor', text: 'Correct — fixed 3 branches, classify, no aggregation. Notice: same topic (travel), different pattern. The pattern is set by the structure, not the topic. Two left — parallelization (A: run grammar / fact / tone checks at once and merge; B: ask the same question 5 times and take the majority) and evaluator-optimizer (a copy bot writes, another model scores it, it revises, repeat).' },
      { who: 'Nick', text: 'a - parallelization, b - evaluator-optimizer.' },
      { who: 'Tutor', text: 'Both right. Parallelization has two flavors — sectioning (independent tasks at once, then merge; for speed) and voting (same task N times, majority; for confidence). Easily confused: voting (independent parallel repeats, no critic, no improvement) vs evaluator-optimizer (generate → critique → revise loop). All 5 patterns done solo.' }
    ]
  },
  {
    id: 't-d1-s3', dom: 'D1', ses: 'S3', date: '2026-07-18', title: 'Orchestrator vs Routing, and the Agent Boundary (interactive)',
    note: 'English translation of the original Korean session. Raw turns — including a vague answer that got sharpened, which is where it clicked.',
    turns: [
      { who: 'Tutor', text: 'System A: a support bot classifies every message into {billing, technical, account} and sends it to a prebuilt handler; the 3 categories are hardcoded. System B: a coding assistant asked "add OAuth login" inspects the codebase, decides on the spot which 4 files to change, delegates each to a worker, and integrates. For each — routing or orchestrator-workers? And the single deciding property in one sentence?' },
      { who: 'Nick', text: 'A routing, B orchestrator-workers.' },
      { who: 'Tutor', text: 'Both labels correct — but you gave only the labels. The point is WHY. A ladder: before any request arrives, can you write down System A’s full list of possible destinations? Can you write down System B’s full list of subtasks? Yes/no each, then the difference in one sentence.' },
      { who: 'Nick', text: 'A yes, B no. Routing = there are predefined branches and you take the input and clarify which one it connects to. Orchestrator-workers = you hold several capabilities and, depending on the input, strategically decide which capability to use and how.' },
      { who: 'Tutor', text: 'The deciding property IS that yes/no. Routing sentence is right. One sharpening: "decide which capability to use" also describes routing (routing also picks one capability), so that phrasing does not separate them. The real split is two tells — routing = pick ONE from an enumerable set of bins (no aggregation); orchestrator = assemble the subtask SET at runtime, then MERGE. So the line is not "which does it pick" but "can you enumerate the list up front + is there a merge". Trap: a ticket is classified into {billing, technical, account}; if technical, a second classifier picks one of {network, hardware, software, account-security}; it goes to exactly one specialist; nothing is combined. Routing or orchestrator?' },
      { who: 'Nick', text: 'Your question is routing. And I see that the core of orchestrator-workers is re-assembling / re-composing the subtasks, and I need to express that clearly.' },
      { who: 'Tutor', text: 'Correct — even nested, every destination is enumerable, exactly one arrives, no merge = routing. Trap avoided. Now Step 2, the apparent paradox: an orchestrator "decides at runtime" too, yet we still call it a workflow. Compare two versions of System B. ① Orchestrator: decompose once (4 files) → workers → merge → done. ② Something else: edit auth.js → run tests → see a failure → open config.js (not in the plan) → fix → re-test → repeat until it decides it is done and stops. What does ② have that ① does not — in one sentence?' },
      { who: 'Nick', text: 'In ② the skeleton is not fixed and it builds the method of solving the mission as it goes?', wrong: true },
      { who: 'Tutor', text: 'Right direction, but a trap: an orchestrator ALSO "builds the method" (it assembles the subtask list), so that phrase does not separate ① and ②. Narrow it to one thing: the feedback loop. ② observes the result of its own action (a test failure), decides the next action from that result, and decides when to stop. ① has no such loop (one pass). Two markers: (1) environment feedback drives the next step, (2) the model decides trajectory length and stop condition. Conclusion: orchestrator = dynamic content / fixed one-pass control flow · agent = the control flow itself is dynamic (feedback loop + self-stop). HW lens: ① = directed regression dispatched once; ② = constrained-random + coverage-closure (observe → next stimulus → loop). APPLY: a pipeline decides per document which fields exist (varies), extracts each with a sub-call, assembles JSON, once, no re-check. Orchestrator or agent, and by which marker?' },
      { who: 'Nick', text: 'Orchestrator, because there is no feedback loop.', correct: true },
      { who: 'Tutor', text: 'Perfect — you cut through the trap ("decides at runtime" tempts you toward agent) with the marker. It is only dynamic content; with no feedback loop it stays a workflow. D1 orchestration slice → confidence 4. Next: D1-S4, multi-agent systems (coordinator ↔ subagents, context isolation).' }
    ]
  },
  {
    id: 't-d1-s4', dom: 'D1', ses: 'S4', date: '2026-07-19', title: 'Multi-agent Systems & Context Isolation (interactive)',
    note: 'English translation of the original Korean session. Raw turns — including a blanked recall that was reconnected, which is where it re-anchored.',
    turns: [
      { who: 'Tutor', text: 'RECALL. Q1: before running, what single question tells you whether a system is a workflow or an agent? Q2: an orchestrator already "decides subtasks at runtime" — what one ingredient must be added for it to become a true agent?' },
      { who: 'Nick', text: 'Q1: not sure. Q2: feedback loop.', wrong: true },
      { who: 'Tutor', text: 'Q2 is right (feedback loop). Q1 is actually half-answered by Q2 — same spine. Reconnect: if before running you can write down the whole step sequence and hardcode it → what is it? If instead the model looks at each result and decides the next step (your feedback loop) → what is it? Complete it as one "… = workflow / … = agent" litmus.' },
      { who: 'Nick', text: 'Workflow = process by a defined, fixed order of steps. Agent = proceed to the next action based on result feedback.', correct: true },
      { who: 'Tutor', text: 'Complete and correct — Q1 was not lost knowledge, just an unlinked connection. Now the topic. Bridge from S3: if each "worker" in orchestrator-workers is itself a full agent (own loop, tools, context), that is a multi-agent system — a coordinator (lead) plus subagents. Scenario: "compare 5 NPU vendors and recommend one" → the coordinator spawns 5 subagents (one per vendor), each investigates independently and returns only a summary, then the coordinator synthesizes. Question: instead of giving each subagent its own context window, you run all five investigations in ONE shared thread — what goes wrong, and what is your HW instinct for why separate contexts help?' },
      { who: 'Nick', text: 'In a shared thread, the info about the five different entities is likely not perfectly separated.' },
      { who: 'Tutor', text: 'Correct — reason 1, cross-task interference / context pollution: attention blurs and vendor A’s numbers get stuck onto B. HW lens: cross-talk on a shared bus; isolation = a local buffer per lane, only summaries written back. Now the second, more physical reason: a context window is a fixed-size buffer (say 200k tokens). If all five subagents must push their full datasheet reads into ONE window, what breaks in terms of CAPACITY, and how does "own window + return only a summary" solve it?' },
      { who: 'Nick', text: 'The context each subagent can handle is limited in inverse proportion to the number in parallel. The capacity shortage lowers each result’s quality or stretches total time, and cramming into a small window triggers auto-compaction, which ironically re-spends tokens repeatedly.' },
      { who: 'Tutor', text: 'Correct, and the auto-compaction catch is especially sharp. Locking it: shared window = each subagent ≈ window÷N (starved), overflow → truncation + repeated compaction. Isolated = each gets a FULL window, goes deep, returns only a summary → the coordinator holds 5 summaries, not 5 raw datasheets. Key line: isolation multiplies total usable context to ≈ N×window while no window is polluted. Last piece — the cost. The same isolation that blocked interference makes A and B work blind to each other. What new problem does that "blind isolation" create that a single shared agent would not suffer? (As a team lead: split work among 5 people with no shared context — what breaks?)' },
      { who: 'Nick', text: 'Each does the common work separately — inefficient overall. And over time they proceed in their own direction rather than to a shared standard.' },
      { who: 'Tutor', text: 'Exactly — (1) duplicated work → token blow-up (the main reason multi-agent runs ~15× a single chat), (2) drift → inconsistency → the coordinator must reconcile. The lever: the coordinator gives very crisp task specs (objective, output format, boundaries, non-overlapping). APPLY: X = "survey NPU dataflow architectures across 20 papers and summarize trends"; Y = "rename one signal that threads through 8 files, keeping every edit consistent". Which fits multi-agent, which does not, and why (interference/capacity gain vs duplication/drift cost)?' },
      { who: 'Nick', text: 'X is the better fit for multi-agent.' },
      { who: 'Tutor', text: 'Right (X = multi). You gave only the label — finish it: what about Y, and one-sentence why for each (tie Y to the drift/inconsistency you named). Hint: X’s pieces are independent (20 papers are strangers), Y’s are interlocked (one signal across 8 files, edits must stay consistent).' },
      { who: 'Nick', text: 'For renaming a signal across modules, you could set the standard in one place first and then do the other seven files in parallel as multi-subagents — but the cost outweighs what you gain from going multi. Sequential in one place is better.' },
      { who: 'Tutor', text: 'Perfect — Y = single agent. Knowing you COULD force it parallel and rejecting it on cost/benefit is exactly the right judgment. Rule, in your words: independent + breadth → multi; coupled/sequential (shared state) → single. Litmus: can the pieces run without seeing each other’s work? Exam angle: multi-agent-research-system is one of the 6 scenarios; the trap (a rerun of S1) is "multi looks powerful, use it by default" — wrong, because of 15× tokens + coordination failure modes.' },
      { who: 'Tutor', text: 'BONUS — the summary boundary. Subagents dig deep in their own window but hand up only a summary; their raw context is isolated and then gone, so the coordinator must trust the summary. HW-verification lens: a block that hands up only pass/fail or a coverage summary, not the full waveform. Q1: what reliability risk does the coordinator now carry? Q2: to trust that summary, what would you, as a verification engineer, require it to include?' },
      { who: 'Nick', text: '1. The process detail disappears — it is hard to know how the result was reached or how to reproduce it. 2. Have the subagent report its verification method, a result report, and its own reliability self-assessment.' },
      { who: 'Tutor', text: 'Correct — the risk is lost provenance/reproducibility, plus baked-in error (the coordinator cannot cross-check) and compounding across layers (same root as S1’s "agents accumulate errors"). Your fix is good, with one sharpening: self-assessment alone is weak — an agent can be confidently wrong — so pair self-confidence with traceable evidence/citations and an independent check. HW lens: never take a DUT’s self-reported pass; require an independent scoreboard and the raw waveform on demand. Conclusion: structure the return (claim + evidence + source + confidence) and run an independent verification pass on the synthesis. This lossy handoff is where reliability leaks — a preview of D5.' }
    ]
  },
  {
    id: 't-d1-s5', dom: 'D1', ses: 'S5', date: '2026-07-19', title: 'Keeping an Agent on the Rails (interactive)',
    note: 'English translation of the original Korean session. Raw turns, with the tutor’s corrections and deepenings kept in full (at Nick’s request).',
    turns: [
      { who: 'Tutor', text: 'RECALL Q1 (re-drill, no hints): state the single litmus for workflow vs agent as one "… = workflow / … = agent" line. Q2: for the coordinator to trust a subagent’s summary, what must the summary include — and why isn’t the subagent’s own "I’m confident" enough?' },
      { who: 'Nick', text: 'Q1: feedback loop. Q2: evidence of the result (test method and a report like a checklist, plus the logical reason behind the subagent’s confidence).' },
      { who: 'Tutor', text: 'Q1 correct — "feedback loop" is the deciding marker, and you retrieved it unaided this time (re-drill passed). Full litmus, nailed down: before running, can you predict/hardcode the path and step count? Yes = workflow; No + the model decides the next step from feedback = agent. Q2 correct, with two additions: (a) traceable source/citations so it can be independently reproduced/verified (yesterday’s provenance); (b) the real reason self-confidence is weak — it is not INDEPENDENT: an agent grading its own work will confidently pass itself when wrong, so an evidenced return must be paired with an independent check. That independent check is today’s door.' },
      { who: 'Tutor', text: 'LEARN. Take S3’s coding agent (edit → test → fail → fix → repeat → self-stop). If you just let it run, how does it go wrong? List the failure modes from your 20 years of building self-running loops. (Axes: does it terminate / is it correct / is it on-goal / is cost bounded?)' },
      { who: 'Nick', text: 'Side-effects of a self-running agent: (1) Without understanding the essential/foundational root cause, it chases the surface symptoms and keeps patching, forcing together a pile of work-arounds. (2) Across many rounds of feeding back to itself it forgets the original goal and repeatedly debugs a NEW problem it created while debugging — and when auto-compaction happens, the chance of forgetting the goal grows. (Also: please keep the tutor’s added explanations clearly in the app and session logs, not just my answers.)' },
      { who: 'Tutor', text: 'Both are deep. Names: (1) root-cause blindness → work-around accretion (symptom-chasing = quality/correctness erosion); (2) goal drift + debugging self-inflicted problems + compaction amnesia (direction/memory failure). You hit the correctness and direction axes hard. Completing the failure map with the rest: Axis 1 terminate → non-termination / oscillation (infinite loop, or fix-A-breaks-B ping-pong); Axis 2 correct → your work-arounds + confidently-wrong "done"; Axis 3 on-goal → your drift/amnesia; Axis 4 cost → token/time/money runaway; Axis 5 in-bounds → scope/permission overreach (destructive or out-of-scope actions). APPLY: map one control to each of the five axes.' },
      { who: 'Nick', text: '1. terminate? stop condition. 2. correct? verification. 3. on-goal? HITL. 4. cost bounded? budget. 5. in-bounds? guardrails.' },
      { who: 'Tutor', text: '1, 2, 4, 5 are exactly right. Refining 3: HITL is not tied to one axis — it is a backstop that cuts across (it can catch drift, wrong-done, and overreach). The tightest control for goal-drift specifically is persistent goal re-anchoring — store the objective/spec in durable state and re-inject it every loop, which is the antidote to your "auto-compaction forgets the goal." HITL sits above that as a safety net. Two deepenings: (a) Axis-2 verification’s crux is INDEPENDENCE — a self-graded pass is worthless; use programmatic checks (tests/schema/linters), a separate evaluator agent (that IS S3’s evaluator-optimizer), or citation checks; and stop + verify are one thing — "done" must mean a verifiable success criterion, or the loop just stops on a wrong answer. (b) HITL does not belong everywhere (a human at every step kills the agent’s value) — so where? APPLY: the coding agent can now edit, test, AND git push + deploy to prod (budget, stop, guardrails already in place). Where does the human checkpoint go, and why there and not every step? (hint: which actions are reversible vs irreversible?)' },
      { who: 'Nick', text: 'I think when one big task finishes and the next begins, a human review and decision touches cost, goal, guardrails, and the reminder all at once, so HITL there is more efficient than agent autonomy.', note: 'a more detailed earlier answer was lost to a device-sync issue and re-sent' },
      { who: 'Tutor', text: 'That is a valid placement — the milestone / phase-boundary gate — and your reasoning is right: one review at that seam covers cost + goal + guardrails + re-anchor together, so it batches human attention efficiently. But that is the "when in the timeline" axis; my hint pointed at a different axis — reversibility — and the two must combine. Narrowing to the scenario: in edit → test → git push → deploy-to-prod, which action is the point of no return, and can its human check wait for a phase boundary?' },
      { who: 'Nick', text: 'A human check before deploy is a must, and ideally a person should approve before push too.' },
      { who: 'Tutor', text: 'Exactly — that is the irreversibility gate. Push/deploy are points of no return, so a human must approve right before them; it cannot wait for a phase boundary because once it is out, it is done. Everything reversible and low-stakes runs autonomously. The two principles compose: milestone gate (oversight efficiency) + irreversibility gate (safety). S5 control map: terminate → stop (max-iter / verifiable success / budget); correct → independent verification (programmatic / evaluator / citations, and "done" = a verifiable criterion); on-goal → re-anchor (durable state + re-inject); cost → budget cap; in-bounds → guardrails; cross-cutting → HITL (milestone + irreversible). HW lens: a regression’s timeout, an independent scoreboard, the test-plan goal, a compute budget, assertions/bounds, and sign-off before tape-out. Exam angle: this is the backbone of "the agent is autonomous — how do you trust it?", and "irreversible/high-stakes actions need human approval" is both a recurring answer and a real safety principle.' }
    ]
  },
  {
    id: 't-d1-s6', dom: 'D1', ses: 'S6', date: '2026-07-19', title: 'The Complexity Ladder — D1 capstone (interactive)',
    note: 'English translation of the original Korean session. Tutor corrections kept in full.',
    turns: [
      { who: 'Tutor', text: 'RECALL / bridge. Two traps: S1 "more autonomy isn’t always better" + S4 "more agents isn’t always better." What single principle do they share? One sentence.' },
      { who: 'Nick', text: 'Based on understanding how things operate — especially agent behavior (as in Claude Code) — you need to choose a work approach that fits each task’s topic and state.' },
      { who: 'Tutor', text: 'Half right — situational fit is correct (and Claude Code is a concrete agent example). The missing half: that fit has a DEFAULT DIRECTION. Both traps point the same way — start with the simplest thing, and treat complexity (autonomy, agent count) as a cost, not a free upgrade; every rung up is justified only when the task forces it. So: don’t reach higher than the task needs. The ladder (you already own all four rungs): augmented LLM (one call + tools) → workflow (the 5 patterns) → single agent (feedback loop) → multi-agent (coordinator + subagents). Power rises, and so do cost and failure surface. Rule: pick the lowest rung that solves the task; climb only when the current rung genuinely cannot. APPLY: extract {date, vendor, total} from invoice PDFs, 10k/day, formats varied but bounded. What is the lowest rung, and what does climbing to an agent cost?' },
      { who: 'Nick', text: 'An augmented LLM is plenty to extract JSON from the invoice PDF. A workflow would also do the job efficiently. A single agent would add almost no cost, I think. Multi-agent could have serious side effects: 10k similar, simple jobs each handled by its own agent means wasted duplicate common work, plus conflicts when merging into one file and extra effort to avoid them.' },
      { who: 'Tutor', text: 'Lowest = augmented LLM (correct), workflow also fine, and your multi-agent analysis (duplicate common work + merge conflicts + coordination overhead) reuses S4 exactly. One correction — the crux of today: "a single agent adds almost no cost" is wrong. An augmented LLM is ~1 call per item; a single agent is a LOOP (decide → act → observe → repeat) = N calls per item. So latency/tokens multiply by N — and at 10k/day that N is multiplied again by 10,000; a "small" per-item overhead is amplified by volume. Also nondeterminism: the agent picks its own path, so identical invoices can take different routes, losing the reproducibility a bounded extraction wants. And you inherit the S5 control burden (stop/verify/guardrails) for flexibility the task never needed. So augmented LLM → agent is not free — it is exactly "reaching one rung too high" (workflow is still predictable and cheap, so it is fine). Capstone climb triggers: augmented → workflow (multi-step but path predictable) / workflow → single agent (path not predefinable, model decides next step from feedback) / single → multi (independent + breadth, exceeds one window). One line: start at the lowest rung, know each climb’s cost, climb only when the task forces it. That closes D1’s first pass (S1–S6).' }
    ]
  }
];

window.CCARF_TRANSCRIPTS = TRANSCRIPTS;
